### ISSUE TITLE
[bug]savepic_sqlurl应该如何配置

### ISSUE THREAD

**Issue by yhrbjsy** [Yan-Zero/nonebot-plugin-savepic#2]
若未配置在应用启动时会报响应错误：Failed to import "nonebot_plugin_savepic"
Traceback (most recent call last):
  File "/home/zhenxun_bot-main/bot.py", line 17, in <module>
    nonebot.load_plugins("extensive_plugin")
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-xRHTbRVY-py3.10/lib/python3.10/site-packages/nonebot/plugin/load.py", line 50, in load_plugins
    return manager.load_all_plugins()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-xRHTbRVY-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 176, in load_all_plugins
    return set(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-xRHTbRVY-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 177, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-xRHTbRVY-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 146, in load_plugin
    module = importlib.import_module(
  File "/root/.pyenv/versions/3.10.0/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-xRHTbRVY-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 242, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/zhenxun_bot-main/extensive_plugin/nonebot_plugin_savepic/__init__.py", line 19, in <module>
    from .pic_sql import savepic, rename, delete, write_pic, randpic, load_pic, select_pic
  File "/home/zhenxun_bot-main/extensive_plugin/nonebot_plugin_savepic/pic_sql.py", line 17, in <module>
    p_config = Config.parse_obj(gdriver.config)
  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
    return cls(**obj)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for Config
savepic_sqlurl
  field required (type=value_error.missing)

**Comment by Xiao-yux** [comment]
![image](https://github.com/Yan-Zero/nonebot-plugin-savepic/assets/79674967/058d61cb-2a0b-40a2-b1c8-61703aefa530)
我使用datastore_database_url的路径后不报这个错了，但最后运行不了
![image](https://github.com/Yan-Zero/nonebot-plugin-savepic/assets/79674967/ebbc73fb-cce0-4c94-af87-007c12de2402)

**Comment by Xiao-yux** [comment]
又去改了改
![image](https://github.com/Yan-Zero/nonebot-plugin-savepic/assets/79674967/40833867-5f01-4ec1-bbd8-24369aaea177)
![image](https://github.com/Yan-Zero/nonebot-plugin-savepic/assets/79674967/ed837f42-5ddf-443a-bb6f-8f415bf403ef)

**Comment by Yan-Zero** [comment]
@Xiao-yux @yhrbjsy
呃啊，因为项目被构建得很复杂所以很久没有push了
塞了一堆 AI 的 API 进去

我这就加个开关（

**Comment by Xiao-yux** [comment]
![image](https://github.com/Yan-Zero/nonebot-plugin-savepic/assets/79674967/da768688-4b02-4ed7-a4b7-89ba71a705ce)
这个错怎么办

**Comment by Yan-Zero** [comment]
emmmm，我之前写的时候应该都是拿pgsql测试的
我看看发个小补丁行不行

**Comment by Yan-Zero** [comment]
pip install git+https://github.com/Yan-Zero/nonebot-plugin-savepic.git
这个可以直接从仓库更新，就改了一句代码（

**Comment by Yan-Zero** [comment]
屎山重写了，现在只支持 pgsql
